# GitHub Actions Workflow (Example)
# This is an example for GitHub Actions - adapt for your CI/CD platform

name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
      
    - name: Generate MDX index
      run: npm run generate-mdx
      
    - name: Build
      run: npm run build
      
    # Add your deployment steps here
    # - name: Deploy
    #   run: npm run deploy
