// This file is auto-generated by scripts/generate-mdx-index.js
// Do not edit manually - your changes will be overwritten!
// To add a new article, create a .mdx file in /content/writing/ and run: npm run generate-mdx

export const designIsTheMoat = `---
title: Design Is The Moat
description: Over the last few days, I've been "vibe coding" some ideas. Building quick prototypes without overthinking. What surprised me wasn't how fast I could move, but how easy it has become to build something that actually works.
publishDate: 15.Nov.2025
modifiedDate: 15.Nov.2025
author: Akash Bhadange
ogImage: https://designerdada.com/media/og-images/design-is-the-moat.jpg
keywords: design, product design, AI, prototyping, startups
---

Over the last few days, I've been "vibe coding" some ideas. Building quick prototypes without overthinking. What surprised me wasn't how fast I could move, but how easy it has become to build something that actually works. Thanks to AI, spinning up fully functional tools and products is no longer reserved for engineers with years of experience. It's now possible for someone like me, a designer with a decent grasp of CSS and layout to ship production-ready apps/tools.

## The New Reality of Building

This shift changes everything. When anyone can code, the barrier to entry drops to zero. The market floods with products that work well enough. Features that once took months can now be replicated in days. The technical moat disappears.

### What This Means for Builders

- Rapid prototyping has become accessible to everyone.
- AI tools enable non-engineers to create functional products.
- Designers can now ship production-ready applications with ease.
- The process is faster and more intuitive than ever before.

### The Design Advantage

But here's where design becomes the real differentiator. When everyone can build something functional, what makes people choose your product? It's the experience. The thoughtfulness. The way it feels. These are things AI can't easily replicate because they require taste, judgment, and a deep understanding of human behavior.

1. Understanding user psychology and behavior patterns
2. Creating emotional connections through thoughtful interactions
3. Making complex things feel simple and intuitive
4. Building trust through consistent, polished experiences

---

> Design is no longer just about making things pretty. It's about creating an experience so good that people choose your product even when alternatives exist.

## Building with Intention

The best products aren't just well-designed interfaces. They're well-designed systems that consider every touchpoint, every interaction, every moment of friction. They understand that design isn't decoration—it's the architecture of experience.

As AI makes building easier, design thinking becomes more valuable. Not just visual design, but product design. Service design. Experience design. The kind of design that asks "should we build this?" before "how do we build this?"

### The Path Forward

So if you're a designer who can code (or a coder learning design), you're in the perfect position. You can move fast *and* create something people actually want to use. You understand both the "what's possible" and the "what feels right."

The future belongs to builders who understand that in a world where anyone can make something that works, the real competitive advantage is making something that people **love**.
`;

export const growthWithoutHacks = `---
title: Growth Without Hacks
description: Real growth isn't about tricks or shortcuts. It's about building something people genuinely want and making it easy for them to tell others about it. Here's how to grow sustainably.
publishDate: 05.Nov.2025
modifiedDate: 05.Nov.2025
author: Akash Bhadange
ogImage: https://designerdada.com/og-images/growth-without-hacks.jpg
keywords: growth, marketing, startups, product development
---

Real growth isn't about tricks or shortcuts. It's about building something people genuinely want and making it easy for them to tell others about it.

## The Problem with Growth Hacking

Growth hacking sounds sexy. Quick wins. Explosive growth. Viral loops. But here's the reality: most growth hacks don't work long-term. They're band-aids on a product that doesn't quite work yet.

### Why Hacks Fail

- They prioritize metrics over user value
- They create unsustainable expectations
- They attract the wrong users
- They burn out your team

## The Alternative: Product-Led Growth

Instead of chasing hacks, focus on making your product so good that people naturally want to share it. This is harder but more sustainable.

### What Makes People Share?

1. **The product solves a real problem** - Not a problem you invented, but one they actively feel
2. **It's delightfully easy to use** - No friction, no confusion, just works
3. **It makes them look good** - Sharing it makes them seem smart or helpful
4. **It saves them time or money** - Tangible value they can point to

---

> The best growth strategy is to build something people love and get out of their way.

## Build Distribution Into the Product

Think about how people discover and share your product naturally. Don't force it, enable it.

### Examples of Natural Distribution

When you build with [Peerlist](https://peerlist.io), your profile is public and shareable. We didn't need to add sharing buttons—people wanted to share because it made them look good. The product *is* the distribution channel.

The same with AutoSend. Every email sent includes subtle branding, but only if the sender wants it. It's opt-in, not forced. People keep it because they're proud of the product.

## Focus on Retention, Not Acquisition

New users mean nothing if they don't stick around. A product with 100 weekly active users who love it beats 10,000 one-time visitors who bounce.

### Retention Metrics That Matter

- Are people coming back?
- Are they using it more over time?
- Would they miss it if it was gone?
- Are they recommending it to others?

If the answer to these is "no," you don't have a distribution problem. You have a product problem.

## The Compound Effect

Sustainable growth feels slow at first. You're not going viral. You're not on the front page of everywhere. But you're building something real.

**Month 1**: 10 users who love your product  
**Month 2**: 25 users (10 stayed + 15 new)  
**Month 3**: 60 users (25 stayed + 35 new)  
**Month 6**: 500 users  
**Month 12**: 5,000 users  

This compounds. And unlike growth hacks, it keeps going.

### Building for the Long Term

The unsexy truth about growth:

1. Build something people want
2. Make it easy to use
3. Help people get value quickly
4. Listen to feedback and iterate
5. Be patient

There's no magic formula. No secret hack. Just consistent, focused work on making your product better every day.

---

## When to Think About Growth

Only after you have retention. If people aren't coming back, nothing else matters. Fix that first.

Once people are sticking around, once they're telling friends, *then* you can think about growth tactics. But even then, keep it simple:

- Write about what you're building
- Show up where your users hang out
- Make it easy to share
- Celebrate your community

The best marketing is a product people want to talk about. Everything else is noise.
`;

export const makeSomethingYouWant = `---
title: Make Something YOU Want
description: The best products come from personal frustration. When you build something you actually need, you understand the problem deeply, you know what's missing, and you have the motivation to make it great.
publishDate: 01.Nov.2025
modifiedDate: 26.Nov.2025
author: Akash Bhadange
ogImage: https://designerdada.com/og-images/make-something-you-want.jpg
keywords: product development, startups, entrepreneurship, design
---

We are builders. We always wants to build something. We have unlimited ideas. Which creates confusion. Confusion to the level that we end up building nothing!

Happens to every one of us where we can't decide on what to build. Maybe as a startup idea or even a simple side project.

I see a lot of posts on Peerlist as well, where people ask for ideas. My simple answer is always - build something you would use every day. This statement is not mine by the way. I read it, and it stuck with me.

Solve a simple problem for yourself. Be your own first user. It helps!

There are so many **[side projects](https://peerlist.io/launchpad)** launching on Peerlist every week. Most of the top projects are simple ideas with great execution solving a personal problem of that developer or designer. These side projects are the most loved ones. Because they are relatable.

When you build something for yourself, you are motivated to make it the best it can be. You know exactly what you need and what works for you. This personal touch makes your project more genuine and useful. Others who face the same problem will see the value in your solution.

Think about the tools and apps you use daily. Many of them started as small projects to solve a problem the creator faced. Gmail was created because the developers were frustrated with existing email services. Slack was built to solve communication issues within a team. These solutions were born out of necessity and grew into something much bigger.

By building something you would use, you create a strong foundation. Your passion and need drive you to keep improving it. You will find joy in using what you've built, and this satisfaction will fuel your drive to keep going.

So, the next time you're stuck on what to build, look inward. What problem do you face every day? What tool or service would make your life easier? Start there. Build it for yourself, and let others benefit from your solution.

In the end, the best projects come from a place of genuine need and personal experience. Build something you would use, and you'll find that others will want to use it too. Your simple, relatable solution might just become the next big thing.

Lastly - Here's Jack Dorsey on why building something for yourself can be better than trying to solve a problem.

<iframe width="560" height="315" src="https://www.youtube.com/embed/tA6MB1y1DDM" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
`;

export const stopFictionalCaseStudies = `---
title: Stop Writing Fictional Case Studies
description: Dear product designers, stop writing fictional case studies and start collaborating with developers on side projects to build credible proof-of-work.
publishDate: 26.Nov.2025
author: Akash Bhadange
ogImage: https://designerdada.com/media/og-images/stop-fictional-case-studies.jpg
keywords: product design, portfolio, case studies, collaboration, career advice
---
I have been noticing a growing trend in designers spending a lot of time working on fictional case studies. Where they come up with an imaginary solution, for some imaginary problem. It's useless, mostly!

If you want to be a UI designer, go ahead and do that. No issues. But if you're training yourself to be a product designer—continue reading.
We all know how difficult the job market is right now. Layoff news coming in from all sides. Early stage companies are hiring, but very conservatively. And if it's a designer role, you need to be more than extraordinary to make a cut because of the cut-throat competition. Especially for the entry level roles.

I am writing this piece of advice for the newcomers. The ones who are looking for their first design job. Folks, you are competing with designers with 2-4 years of experience. And your fictional case studies won't help to "stand out".
This essay is not about how to design your portfolio, it's very specific about your proof-of-work as a product designer.

So, **what** will help you to be exceptional?

Work on real problems, build real solutions for real users!

Now you will ask **how**?

Many developers launch their [side projects on Peerlist](https://peerlist.io/projects?ref=designgiri.com). Many of them need help with design. (Sorry devs, but you really do!)

Connect with them. Convince them. Show them how your designs make their project super useful. Collaborate with them. This is important. Collaborate.

Now the most important question — **WHY**?

Well, they are building something which will be used by real people. Not millions, but hundreds for sure. Help them validate the problem. Help them design the solution. Help them improve the aesthetics. Collaborate with them!

Trust me, these developers will help you become a better designer. They will teach you what "technical constraints" are and tell you the real meaning of "edge cases".

Now document your learnings after collaborating on this side project. Present it as a case study. It's your proof-of-work which is highly credible! Your design is functional in an actual browser or an app. Not just a screenshot in a fancy free mockup.

Imagine you're sitting in an interview and discussing all your learnings while building this project. Telling stories about how a simple copy change improved the conversion from a landing page. Talking about user research, unexpected insights and how you convinced the developer to implement that fancy animation.

As a hiring manager, I will "hard relate" to these stories. Because you are not only talking only about the outcome but the actual impact of your design.

Just find a developer who is working on a side project or share that you're open to collaboration. You just need one or two such projects on your portfolio. I am sure a design manager will be interested in chatting with you.

Because you will stand out!

All the best!

---

If you have read till here, I have 2 asks from you —
- Share this with your designer peers.
- Also read [portfolio advice](https://hvpandya.com/portfolio-advice?ref=designgiri.com)by[Hardik Pandya](https://peerlist.io/hardikpandya?ref=designgiri.com). It's a good one.
`;

// Map of all articles
export const allMDXContent: Record<string, string> = {
  'design-is-the-moat': designIsTheMoat,
  'growth-without-hacks': growthWithoutHacks,
  'make-something-you-want': makeSomethingYouWant,
  'stop-fictional-case-studies': stopFictionalCaseStudies,
};
